# Generated by Django 4.2.16 on 2024-11-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auser_performancedata_userengagement_userbehavior_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("location", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("segment", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(model_name="churndata", name="user",),
        migrations.RemoveField(model_name="eventtracking", name="user",),
        migrations.DeleteModel(name="PerformanceData",),
        migrations.RemoveField(model_name="useractivity", name="user",),
        migrations.RemoveField(model_name="userbehavior", name="user",),
        migrations.RemoveField(model_name="userengagement", name="user",),
        migrations.DeleteModel(name="AUser",),
        migrations.DeleteModel(name="ChurnData",),
        migrations.DeleteModel(name="EventTracking",),
        migrations.DeleteModel(name="UserActivity",),
        migrations.DeleteModel(name="UserBehavior",),
        migrations.DeleteModel(name="UserEngagement",),
    ]
