name: Update README

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to update README
        run: |
          python update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          git add -f README.md
          git commit -m "Update README with latest commit and test results" || echo "No changes to commit"
          git push