name: Update README

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate README
      run: python generate_readme.py

    - name: Commit and push if README changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md -f
        git commit -m "Update README.md" || exit 0  # exit 0 if no changes
        git push